# Generated by Django 4.1.1 on 2022-10-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, max_length=15, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('task_start', models.DateTimeField(auto_now_add=True)),
                ('bug_description', models.TextField(max_length=255)),
                ('sender', models.CharField(max_length=50)),
                ('job_description', models.TextField(max_length=255)),
                ('job_doc_number', models.IntegerField(blank=True, null=True)),
                ('task_end', models.DateTimeField()),
                ('task_status', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.object')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dispatcher')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.worker')),
            ],
        ),
    ]
