# Generated by Django 4.1.1 on 2022-10-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name_plural': 'Исполнитель'},
        ),
    ]
