# Generated by Django 4.1.1 on 2022-10-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatcher',
            options={'verbose_name': 'Диспетчер', 'verbose_name_plural': 'Диспетчеры'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
    ]
