# Generated by Django 4.1.1 on 2022-10-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dispatcher_options_alter_object_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
    ]
