# Generated by Django 4.1.1 on 2022-10-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dispatcher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание для СМИ'),
        ),
        migrations.AlterField(
            model_name='object',
            name='latitude',
            field=models.FloatField(blank=True, max_length=15, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='longitude',
            field=models.FloatField(blank=True, max_length=15, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='object',
            name='number',
            field=models.IntegerField(verbose_name='Номер объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.BooleanField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.object', verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='bug_description',
            field=models.TextField(max_length=255, verbose_name='Описание неисправности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dispatcher', verbose_name='Принял диспетчер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='job_description',
            field=models.TextField(max_length=255, verbose_name='Описание выполненных работ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='job_doc_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер акта выполненных работ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.IntegerField(verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sender',
            field=models.CharField(max_length=50, verbose_name='Кто передал'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=True, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.worker', verbose_name='Назначен исполнитель'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
    ]
