# Generated by Django 4.1.1 on 2022-10-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_object_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание выполненных работ'),
        ),
    ]
