# Generated by Django 4.1.1 on 2022-10-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dispatcher_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона мобильный'),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_number_worked',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона рабочий'),
        ),
    ]
