# Generated by Django 4.1.1 on 2022-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_worker_phone_number_worker_phone_number_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус заявки'),
        ),
    ]
